config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :trips do
    resources :legs, except: [ :edit, :update, :destroy ]
    resources :point_of_interests do
      resources :legs, only: :destroy
    end
  end

  resources :legs, only: :update

  resources :users, only: [:show, :edit, :update]


  resources :pages, only: [:home]
  get '/dashboard', to: 'pages#dashboard'
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/leg.rb
class Leg < ApplicationRecord
  belongs_to :trip
  belongs_to :point_of_interest
end

app/models/point_of_interest.rb
class PointOfInterest < ApplicationRecord
  has_many :legs
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  has_many :legs
  has_many :point_of_interests, through: :legs

  validates :start_location, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :trips

  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

   def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  def default_url_options
    { host: ENV["HOST"] || "localhost:3000" }
  end

end

app/controllers/legs_controller.rb
class LegsController < ApplicationController
  # def index
  def create
    @trip = Trip.find(params[:trip_id])
    @poi = PointOfInterest.find(params[:poi_id])
    @leg = Leg.new(trip: @trip, point_of_interest: @poi)
    @leg.save
    @pois = PointOfInterest.where(country: @trip.start_location)

    if @trip.legs.any?
      first_leg = @trip.legs.first
      @first_poi = PointOfInterest.find(first_leg.point_of_interest_id)
    end
    # need access to whatever @markers is
    # binding.pry
    @legs = Leg.where(trip_id: params[:trip_id])
    @leg_list = []
    @legs&.each do |leg|
      geocode = [ leg.point_of_interest.lat, leg.point_of_interest.long ]
      @leg_list << geocode
    end
    @leg_list

    respond_to do |format|
      format.html { redirect_to trip_path(@trip) }
      format.js
    end
  end

  def destroy
    # binding.pry
    @trip = Trip.find(params[:trip_id])
    @poi = PointOfInterest.find(params[:point_of_interest_id])
    @poi_id = @poi.id
    @leg = Leg.find(params[:id])
    @leg.destroy

    # @pois = PointOfInterest.where(country: @trip.start_location)
    # @first_poi = @pois.first

    @legs = Leg.where(trip_id: params[:trip_id])
    @leg_list = []
    @legs&.each do |leg|
      geocode = [ leg.point_of_interest.lat, leg.point_of_interest.long ]
      @leg_list << geocode
    end
    @leg_list

    respond_to do |format|
      format.html { redirect_to trip_path(@trip) }
      format.js
    end
  end

  def edit
    @trip = Trip.find(params[:trip_id])
    @leg = Leg.find(params[:id])
  end

  def update
    # @trip = Trip.find(params[:trip_id])
    @leg = Leg.find(params[:id])
    @leg.update(leg_params)
    @trip = Trip.find_by(id: @leg.trip_id)

    @total_stay = (@trip.end_date - @trip.start_date).to_i
    all_los = @trip.legs.map do |leg|
      leg.length_of_stay.nil? ? 0 : leg.length_of_stay
    end
    total_los = all_los.reduce(:+)
    @time_left = @total_stay - total_los
    # binding.pry
    respond_to do |format|
      format.html { redirect_to trip_path(@trip) }
      format.js
    end
  end

  private

  def leg_params
    params.require(:leg).permit(:length_of_stay)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @trip = Trip.new
    @points_of_interest = PointOfInterest.all
  end

  def show
    @user = User.find(current_user[:id])
    @trips = current_user.trips
    @pois = PointOfInterest.all
    # @trips.each do |trip|
    #   @markers = PointOfInterest.where(country: trip.start_location).map do |poi|
    #     [poi.lat, poi.long, poi.name, poi.description, poi.url]
    #   end
    # end
  end

  def dashboard
    @trips = current_user.trips
    @pois = PointOfInterest.all
  end
  # to display mutiple pois in the map
  # current_user.trips.each do |trip|
  #   @markers = PointOfInterest.where(country: trip.start_location).map do |poi|
  #     @array << [poi.lat, poi.long, poi.name, poi.description, poi.url]
  #   end
  # end
end

app/controllers/point_of_interests_controller.rb
class PointOfInterestsController < ApplicationController


  def new
    @poi = PointOfInterest.new
  end

  def create
    @poi = PointOfInterest.new(poi_params)
    redirect_to trip_path
  end

  private

  def poi_params
    params.require(:point_of_interest).permit(:name, :lat, :long, :description, :photo, :url, :type, :country)
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  skip_before_action :authenticate_user!, only: :show

  def show
    @trip = Trip.find(params[:id])
    @pois = PointOfInterest.where(country: @trip.start_location)
    @markers = []
    PointOfInterest.where(country: @trip.start_location).each do |poi|
      @markers << [poi.lat, poi.long, poi.name, poi.description, poi.url, poi.photo]
    end
    @legs = Leg.where(trip_id: params[:id])
    # raise
    @leg_list = []
    @legs.each do |leg|
      geocode = [ leg.point_of_interest.lat, leg.point_of_interest.long ]
      @leg_list << geocode
    end
    @leg_list

    @total_stay = (@trip.end_date - @trip.start_date).to_i

    # if @trip.legs.any?
    all_los = @trip.legs.map do |leg|
      leg.length_of_stay.nil? ? 0 : leg.length_of_stay
    end
    total_los = all_los.length > 0 ? all_los.reduce(:+) : 0
    @time_left = @total_stay - total_los
    # end
    if @trip.legs.any?
      first_leg = @trip.legs.first
      @first_poi = PointOfInterest.find(first_leg.point_of_interest_id)
    end
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.new(trip_params)
    @trip.user = current_user
    if @trip.save
      redirect_to trip_path(@trip)
    else
      redirect_to root_path
    end
  end

  def edit
    @trip = Trip.find(params[:id])
  end

  def update
    @trip = Trip.find(params[:id])
    @trip.update(trip_params)

    @total_stay = (@trip.end_date - @trip.start_date).to_i
    all_los = @trip.legs.map do |leg|
      leg.length_of_stay.nil? ? 0 : leg.length_of_stay
    end

    total_los = all_los.reduce(:+)
    @time_left = @total_stay - total_los
    respond_to do |format|
      format.html { redirect_to trip_path(@trip) }
      format.js
    end

  end

  private

  def trip_params
    params.require(:trip).permit(:name, :description, :user_id, :start_location, :end_location, :start_lat, :start_long, :start_date, :end_date, :travel_type, :photo, :preferred_travel_time)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- <title>Tripper</title> -->
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link href='https://api.mapbox.com/mapbox-gl-js/v0.47.0/mapbox-gl.css' rel='stylesheet' />
    <!-- <link rel="stylesheet" href="/path/to/flickity.css" media="screen"> -->



    <script src='https://npmcdn.com/@turf/turf/turf.min.js'></script>



    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

  </body>
</html>

app/views/legs/_create_button.html.erb
<%= link_to trip_legs_path(trip, poi_id: poi_id), method: :post, id: "CLeg#{poi_id}", remote: true do %>
  <p data-remote="true" class="add-to-trip card-btn add-poi-btn btn btn-primary">Add To Trip</p>
<% end %>

app/views/legs/_destroy_button.html.erb
<%= link_to trip_point_of_interest_leg_path(trip, poi, leg), id: "DLeg#{poi.id}", method: :delete, remote: true do %>
  <p data-remote="true" class="destroy-to-trip card-btn added-poi-btn btn">Added To Trip</p>
<% end %>

app/views/legs/create.js.erb
if (document.getElementById("CLeg<%= @poi.id%>") !== null) {
  document.getElementById("CLeg<%= @poi.id%>").innerHTML = "<%= j render 'legs/destroy_button', trip: @trip, poi: @poi, leg: @leg %>";
}

document.querySelector('.timeline-container').innerHTML = "<%= j render 'trips/trip_timeline', trip: @trip, first_poi: @first_poi %>"

var mapElement = document.getElementById("map");
document.getElementById('map').setAttribute('data-legs', "<%= @leg_list.to_json %>")

// find new legs
var legs = JSON.parse(mapElement.dataset.legs);

mapboxgl.accessToken = 'pk.eyJ1IjoiaGFycnlyeWRlciIsImEiOiJjamxkbDZ6eHYwOGxjM3dydjk4NGlyZHNtIn0.3I7XiB1k09ti1TZ3o2UH3A';

var legDurations = [];
// call api
var api_input = "";
legs.forEach ((leg) => {
  api_input += `${leg[1]},${leg[0]};`
});

api_input = api_input.slice(0, -1);


fetch(`https://api.mapbox.com/optimized-trips/v1/mapbox/driving/${api_input}?access_token=${mapboxgl.accessToken}`)
  .then(response => response.json())
  .then((data) => {
    // console.log(data)
    const tripLegs = data.trips[0].legs
    tripLegs.forEach((leg) => {
      const legDurationsInMinutes = leg.duration / 60
      const legDistancesInKm = leg.distance / 1000
      const minutes = legDurationsInMinutes % 60;
      const hours = (legDurationsInMinutes - minutes) / 60;
      const finalTime = hours + "hr " + Math.round(minutes) + "mins";
      legDurations.push(finalTime)
    })
    // console.log(tripLegs)
    // console.log(legDurations[0]);
    var num = 0;
    document.querySelectorAll(".duration").forEach(function(ptag){
      ptag.innerHTML = `Travel time to next destination: <strong>${legDurations[num]}</strong>`;
      num++;
    });
  });
/////

app/views/legs/destroy.js.erb
if (document.getElementById("DLeg<%= @poi.id%>") !== null) {
  document.getElementById("DLeg<%= @poi.id%>").innerHTML = "<%= j render 'legs/create_button', trip: @trip, poi_id: @poi.id %>";
}

document.querySelector('.timeline-container').innerHTML = "<%= j render 'trips/trip_timeline', pois: @pois, first_poi: @first_poi, trip: @trip %>"

document.getElementById('map').setAttribute('data-legs', "<%= @leg_list.to_json %>")

app/views/pages/dashboard.html.erb
<div class="dashboard-background-img" style="background-image: linear-gradient(135deg, rgba(0,0,0,0.5) 0%, rgba(0,0,0,0.5) 50%), url('https://images.unsplash.com/photo-1507295386538-ddd5e86cd597?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=530c7e3fde63061f540c50986ce2a699&auto=format&fit=crop&w=2378&q=80');">

  <div class="dashboard-header">
    <h6>Your trips</h6>
  </div>

  <div class="white-container">
<!--     <div class="dashboard-cards-wrap">
      <div class="dashboard-cards-container"> -->
        <div class="row">
          <% @trips.each do |trip| %>
            <div class="col-xs-12">
              <div class="dashboard-card">
                <div class="dashboard-card-header">
                  <h5><%= trip.start_location %></h5>
                </div>
                <div class="dashboard-card-button">
                  <%= link_to "Edit trip", trip_path(trip), class: "dashboard-card-btn" %>
                </div>
                <%#= image_tag trip.first.point_of_interests.first.photo, alt: "alttext" %>

                <div class="dashboard-card-image" style="background-image: url('https://images.unsplash.com/photo-1517428401505-14146d0d739c?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=cf66674d50ec9b75de14ec3a5e53e0f5&auto=format&fit=crop&w=1500&q=80');">
                </div>
                <div class="dashboard-card-trip-dates">
                  <p><%= trip.start_date.strftime("%d-%m-%Y") %>   <i class="fas fa-arrow-right"></i>   <%= trip.end_date.strftime("%d-%m-%Y") %></p>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
<!--     </div>
  </div> -->
</div>

app/views/pages/show.html.erb
<div class="dash-container cards-container">

  <div class="row">
    <% @trips.each do |trip|%>
      <div class="col-lg-6 col-md-12 col-xs-12">
        <div class="modal-dialog dashboard-card">
          <div class="modal-content">
            <div class="modal-header">
              <div class="pull-left card-country"><h4><%= trip.start_location %> </h4></div>
              <div class="pull-right"><%= link_to "Edit", trip_path(trip), class: "btn btn-primary btn-dashboard"  %>
              </div>
            </div>
            <div class="modal-body">

              <div  class="carousel slide" id="trip-<%= trip.id %>" data-interval="false">
                <div class="carousel-inner">
                 <div class="item active ">
                    <%= image_tag('japan-mount-fuji.jpg', class: "img-responsive dashboard-card-img") %>
                    <div class="carousel-caption">
                      <h4>See Descriptions </h4>
                    </div>
                  </div>
                  <% @pois = PointOfInterest.where(country: trip.start_location) %>
                  <% @pois.each do |poi| %>

                    <% @legs = Leg.where(point_of_interest_id: poi.id) %>
                    <% @legs.each do |leg| %>
                      <div class="item">
                        <%= image_tag(leg.point_of_interest.photo, class: "img-responsive dashboard-card-img") %>
                        <div class="carousel-caption">
                          <h3><%= leg.point_of_interest.name %></h3>
                        </div>
                      </div>
                    <% end %>
                  <% end %>
                </div>
              </div>
              <a class="left carousel-control" href="#trip-<%= trip.id %>" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
              </a>
              <a class="right carousel-control" href="#trip-<%= trip.id %>" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
              </a>

            </div>
            <!-- <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                  change
                </button>
            </div> -->
             <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <!-- <span aria-hidden="true">&times;</span> -->
                        </button>
                      </div>
                      <div class="modal-body">
                        <%=  simple_form_for(trip) do |f| %>
                          <%= f.input :name %>
                          <%= f.input :description %>
                      <div class="modal-footer">
                          <%= f.button :submit %>
                      </div>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
          </div>
        </div>
      </div>

    <% end %>
  </div>
</div>
</div>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "About", "#{root_path}#about", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Dashboard", dashboard_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%#= link_to "Q&A", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <% if user_signed_in? %>
        <%= link_to 'Logout', destroy_user_session_path, :method => :delete, class:"navbar-wagon-item navbar-wagon-link" %>
      <% else %>
        <%= link_to 'Login', user_session_path, class:"navbar-wagon-item navbar-wagon-link" %>
      <% end %>
      <!-- <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        </ul>
      </div> -->

      <!-- Avatar with dropdown menu -->
      <!-- <div class="navbar-wagon-item">
        <div class="dropdown">
          <%#= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%#= link_to "#" do %>
                <i class="fa fa-user"></i> <%#= t(".profile", default: "Profile") %>
              <#% end %>
            </li>
            <li>
              <%#= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%#= t(".settings", default: "Settings") %>
              <#% end %>
            </li>
            <li>
              <%#= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%#= t(".sign_out", default: "Log out") %>
              <#% end %>
            </li>
          </ul>
        </div>
      </div> -->
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "About", "#{root_path}#about", class: "navbar-wagon-item navbar-wagon-link" %></li>
          <% if user_signed_in? %>
          <li>
            <%= link_to 'Logout', destroy_user_session_path, :method => :delete, class:"navbar-wagon-item navbar-wagon-link" %>
          </li>
          <% else %>
          <li>
            <%= link_to 'Login', user_session_path, class:"navbar-wagon-item navbar-wagon-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/trips/_loading_circle.html.erb
<div class="loading-circle">
    <h5>Nights Left</h5>
    <div id="container" data-daysleft="<%= time_left.to_json %>" data-los="<%= total_stay.to_json %>">
      <p id="days-integer"><%= time_left %></p>
    </div>
</div>

<%= javascript_pack_tag 'circle' %>

app/views/trips/_timeline_content.html.erb
<div class="timeline-content">
<!--   <div class="name-and-delete-icon"> -->
    <h5><%= poi.name %></h5>
    <%#= link_to trip_point_of_interest_leg_path(@trip, poi, leg), id: "DLeg#{poi.id}", method: :delete, remote: true do %>
<!--       <i class="fas fa-trash-alt"></i> -->
    <%# end %>
<!--   </div> -->
  <p><%= poi.description %></p>
  <p class="duration"></p>
  <div class="los_form form-inline">
    <%= simple_form_for leg, remote: true do |f| %>
      <%= f.input :length_of_stay, label: "How many nights would you like to stay?", class: 'length_of_stay form-control' %>
      <%= f.submit 'Confirm', class: 'submit' %>
    <% end %>
  </div>
</div>

app/views/trips/show.html.erb
<script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.48.0/mapbox-gl.js'></script>
<div class="trip-container">

  <div class="cards-wrap">
    <h6><%= @trip.start_location %></h6>
    <div class="cards-container">
      <div class="row">
        <% @pois.each do |poi| %>
          <div class="col-xs-12 ">
            <!-- IF POI ISN`T A LEG -->
            <% if @trip.legs.find_by(point_of_interest_id: poi.id).nil? %>
              <div class="card-live id="<% poi[:name] %>" data-name="<% poi[:name] %>">
                <div class="card-image" style="background-image: linear-gradient(135deg, rgba(0,0,0,0.2) 0%, rgba(0,0,0,0.2) 50%), url('<%= image_path poi.photo %>');">
                  <h5><%= poi.name %></h5>
                </div>
                <div class="collapse card-box" id="collapse-<%= poi[:name] %>">
                  <p><%= poi.description %></p>
                </div>
                <div class="card-btns">
                  <p class="card-btn read-more-btn btn" data-toggle="collapse" data-target="#collapse-<%= poi[:name] %>" id="toggle">Read more</p>
                  <div id="createLeg<%= poi.id %>" class="add-to-trip">
                    <%= render 'legs/create_button', trip: @trip, poi_id: poi.id %>
                  </div>
                </div>
              </div>
              <!-- IF POI IS A LEG -->
            <% else %>
              <div class="card-live" id="<%= poi[:name] %>" data-name="<%= poi[:name] %>">
                <div class="card-image" style="background-image: linear-gradient(135deg, rgba(0,0,0,0.2) 0%, rgba(0,0,0,0.2) 50%), url('<%= image_path poi.photo %>');">
                  <% leg = Leg.find_by(point_of_interest_id: poi.id) %>
                  <h5><%= poi.name %></h5>
                </div>
                <div class="collapse card-box" id="collapse-<%= poi[:name] %>">
                  <p class="open-description"><%= poi.description %></p>
                </div>
                <div class="card-btns">
                  <p class="card-btn read-more-btn btn" data-toggle="collapse" data-target="#collapse-<%= poi[:name] %>" id="toggle">Read more</p>
                  <div data-id="destroyLeg<%= poi.id %>" class="remove-from-trip">
                    <%= render 'legs/destroy_button', trip: @trip, poi: poi, leg: leg %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
          <%= javascript_pack_tag "cards" %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="map-container">
    <div id='map' data-pin = "<%= asset_path('pin.png')%>" data-bluepin = "<%= asset_path('blue-pin.png')%>" data-markers = "<%= @markers.to_json %>" data-legs = "<%= @leg_list.to_json %>"></div>
    <div class="optimize-button">
      <p>Calculate Optimized Route</p>
    </div>
  </div>

</div>



  <div class="timeline-header">
    <i class="fas fa-chevron-circle-down"></i>
    <div class="subheader">
      <h6 id="subheader">Now choose how long you would like to spend in each location</h6>
      <p>P.S. Feel free to edit your trip dates if you think you need more time!</p>
    </div>
  </div>

<!-- note below, if statement to be moved to JS  -->
<%# if @legs.length < 2 %>
<!--   <div class="t-plans-sub-heading">
    <h6 class="subheader">Please choose where you will be flying to and at least one other location</h3>
  </div> -->
<%# else %>
  <div class="itinerary-container">
    <div class="timeline-container">
      <%= render 'trip_timeline', pois: @pois, first_poi: @first_poi, trip: @trip %>
    </div>
  <div class="right-container">
    <div class="edit-trip-form">
      <h5>Edit Trip Dates</h5>
      <div class="form-inline">
      <%= simple_form_for @trip, remote: true do |f| %>
        <%= f.input :start_date, placeholder: 'From', label:false, as: :string, input_html: { class: 'flatpickr-input trip-date-input' } %>
        <%= f.input :end_date, placeholder: 'Until', label:false, as: :string, input_html: { class: 'flatpickr-input trip-date-input' } %>
      </div>
        <%= f.submit 'Confirm', class: 'edit-trip-submit' %>
      <% end %>
    </div>
    <div class="progress-circle">
      <%= render 'loading_circle', time_left: @time_left, total_stay: @total_stay %>
    </div>
    <div class="link-dashboard">
      <%= link_to "Save trip", dashboard_path, class: "dashboard-button" %>
    </div>
  </div>
<%# end %>
</div>

<!--
<script>
  function initUpdateNavbarOnScroll() {
    const navbar = document.querySelector('.right-container');
    if (navbar) {
      window.addEventListener('scroll', () => {
        if (window.scrollY >= window.innerHeight) {
          navbar.classList.add('.date-sticky');
        } else {
          navbar.classList.remove('.date-sticky');
        }
      });
    }
  }
</script> -->

<%= javascript_pack_tag "cards" %>
<%= javascript_pack_tag "map" %>
<%= javascript_pack_tag "timeline" %>
<%= javascript_pack_tag 'datepicker' %>
<%= javascript_pack_tag 'arrow' %>